-- This file allow to write SQL commands that will be emitted in test and dev.
-- The commands are commented as their support depends of the database
-- insert into myentity (id, field) values(1, 'field-2');
-- insert into myentity (id, field) values(2, 'field-2');
-- insert into myentity (id, field) values(3, 'field-3');
-- alter sequence myentity_seq restart with 4;

insert into users (username, apiKey) values ('Benny', '123');
insert into users (username, apiKey) values ('Roger', '8008');
insert into users (username, apiKey) values ('Customer', '0000');


insert into cars (manufacturer, year, model, milage, user_id) values ('Chevrolet', 2006, 'Corvette', 36593, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Subaru', 2008, 'Outback', 46800,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mercedes-Benz', 1996, 'E-Class', 11977,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Nissan', 1993, 'Sentra', 42508, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Nissan', 1997, '200SX', 30828, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Suzuki', 2006, 'XL-7', 46925, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Saturn', 2006, 'VUE', 43190,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Lexus', 2011, 'RX', 5184,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Suzuki', 2006, 'Swift', 45907,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Buick', 2002, 'LeSabre', 48746,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Volkswagen', 2012, 'Jetta', 25074,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Lamborghini', 1986, 'Countach', 3582, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Toyota', 1992, 'Tercel', 30681,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Lexus', 2006, 'LS', 40748, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Volkswagen', 2009, 'Jetta', 46705,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Nissan', 2005, 'Murano', 2499, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Volkswagen', 1987, 'Passat', 15402,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Ford', 2010, 'Flex', 46806, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Ford', 2007, 'Mustang', 26371,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Ford', 1993, 'F250', 17811, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Lexus', 2006, 'ES', 37841,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Audi', 2009, 'Q5', 37404, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mercury', 1996, 'Grand Marquis', 29318, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mercedes-Benz', 2005, 'C-Class', 15445, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mitsubishi', 1991, 'Mirage', 17222, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Chevrolet', 2009, 'Silverado 2500', 24696, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Kia', 2008, 'Rondo', 43650, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Dodge', 1996, 'Ram 1500 Club', 1399,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Chrysler', 2001, 'PT Cruiser', 8641, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Oldsmobile', 1994, 'Ciera', 32343,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Cadillac', 2003, 'Escalade', 40026,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Audi', 2012, 'Q7', 45175,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mercedes-Benz', 2007, 'SL-Class', 36565,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Suzuki', 2001, 'Swift', 28255,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Shelby', 1968, 'GT500', 31459, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Volkswagen', 1976, 'Golf', 49159,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Chevrolet', 1997, 'Blazer', 45669,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mitsubishi', 2003, 'Montero', 39997, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mercury', 1994, 'Cougar', 5408, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Ford', 2011, 'E-Series', 41286,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Honda', 2003, 'Odyssey', 6914, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Dodge', 1999, 'Avenger', 10588, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Hummer', 2001, 'H1', 42750, 1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Ford', 2004, 'Ranger', 19476,1);
insert into cars (manufacturer, year, model, milage, user_id) values ('Acura', 1997, 'CL', 49157,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Land Rover', 2011, 'Range Rover', 30042, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mazda', 2012, 'Mazdaspeed 3', 13316, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Audi', 1996, 'A6', 11687,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Citroën', 1989, 'CX', 2871, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Volvo', 2008, 'C70', 3132,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Nissan', 1996, 'Pathfinder', 46795,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Hyundai', 2004, 'Accent', 48444,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mercury', 1967, 'Cougar', 16865, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mercedes-Benz', 2007, 'S-Class', 37628, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mazda', 1999, 'B-Series Plus', 27596,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Ford', 1993, 'Club Wagon', 47539,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mercury', 1986, 'Capri', 38740, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Morgan', 2006, 'Aero 8', 27694,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Chevrolet', 1992, 'G-Series G20', 43700,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Kia', 2004, 'Spectra', 13057, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mercedes-Benz', 2009, 'SL-Class', 6376,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mitsubishi', 2004, 'Endeavor', 17314, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Acura', 2012, 'TL', 39683, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Isuzu', 1999, 'VehiCROSS', 37335,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Chevrolet', 2001, 'Silverado', 7533, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mazda', 2010, 'Mazda3', 45523, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Suzuki', 2012, 'SX4', 7000, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Ford', 1990, 'E-Series', 11887, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Toyota', 2010, 'Avalon', 27195, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Dodge', 1997, 'Ram 3500 Club', 48520,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Ford', 1991, 'Aerostar', 14324,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('BMW', 2005, '7 Series', 1859,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Volvo', 1997, '850', 40157,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Foose', 2007, 'Hemisfear', 1984,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mercedes-Benz', 2011, 'R-Class', 7951,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Isuzu', 1995, 'Rodeo', 34957,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mercedes-Benz', 1993, '300E', 4732,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Pontiac', 1995, 'Firefly', 20483, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Dodge', 1996, 'Ram Van 3500', 10363,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mazda', 2008, 'MX-5', 33572,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Chevrolet', 2011, 'Camaro', 20822,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Pontiac', 1966, 'LeMans', 15512,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Land Rover', 2003, 'Range Rover', 3915, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Dodge', 2009, 'Ram 3500', 37077,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Kia', 2006, 'Spectra', 34660, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('MINI', 2009, 'Cooper Clubman', 35208,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Mitsubishi', 2008, 'Raider', 44539,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Jaguar', 2003, 'XK Series', 21876, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Volkswagen', 2002, 'Golf', 32518, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Rambler', 1963, 'Classic', 30165, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Volkswagen', 1986, 'Jetta', 36142, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Chevrolet', 2011, 'Aveo', 29455, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Tesla', 2011, 'Roadster', 14554,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Lexus', 2009, 'LX', 43712,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Jaguar', 2011, 'XK', 47221, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Land Rover', 1997, 'Defender 90', 36392, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Audi', 1994, 'riolet', 47399, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Buick', 2011, 'Lucerne', 6127, 2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Maserati', 2011, 'Quattroporte', 46755,2);
insert into cars (manufacturer, year, model, milage, user_id) values ('Dodge', 1997, 'Ram 1500 Club', 20227,2);